// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArrowIcon: typeof import('./components/icons/ArrowIcon.vue')['default']
    AvatarIcon: typeof import('./components/icons/AvatarIcon.vue')['default']
    AvatarList: typeof import('./components/user/AvatarList.vue')['default']
    AvatarsList: typeof import('./components/profile/AvatarsList.vue')['default']
    CatalogCard: typeof import('./components/content-card/CatalogCard.vue')['default']
    CheckIcon: typeof import('./components/icons/CheckIcon.vue')['default']
    ContentCard: typeof import('./components/content-card/ContentCard.vue')['default']
    copy: typeof import('./components/icons/OrganizationIcon copy.vue')['default']
    EmptyState: typeof import('./components/common/EmptyState.vue')['default']
    ListPagination: typeof import('./components/data-lists/ListPagination.vue')['default']
    ListPaginationSkeleton: typeof import('./components/data-lists/ListPaginationSkeleton.vue')['default']
    LogoIcon: typeof import('./components/icons/LogoIcon.vue')['default']
    NavigationMenu: typeof import('./components/header/NavigationMenu.vue')['default']
    OrganizationIcon: typeof import('./components/icons/OrganizationIcon.vue')['default']
    PageHeader: typeof import('./components/common/PageHeader.vue')['default']
    PlusIcon: typeof import('./components/icons/PlusIcon.vue')['default']
    ProfileMenu: typeof import('./components/header/ProfileMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./components/icons/SearchIcon.vue')['default']
    ServiceCard: typeof import('./components/services/ServiceCard.vue')['default']
    ServiceContributors: typeof import('./components/service/ServiceContributors.vue')['default']
    ServiceMetrics: typeof import('./components/service/ServiceMetrics.vue')['default']
    ServicesCatalog: typeof import('./components/services/ServicesCatalog.vue')['default']
    ServicesCatalogSkeleton: typeof import('./components/services/ServicesCatalogSkeleton.vue')['default']
    ServiceStatus: typeof import('./components/service/ServiceStatus.vue')['default']
    ServiceVersionsList: typeof import('./components/service/ServiceVersionsList.vue')['default']
    SettingsIcon: typeof import('./components/icons/SettingsIcon.vue')['default']
    SpinnerIcon: typeof import('./components/icons/SpinnerIcon.vue')['default']
    TheButton: typeof import('./components/common/TheButton.vue')['default']
    TheInput: typeof import('./components/common/TheInput.vue')['default']
    TopBar: typeof import('./components/header/TopBar.vue')['default']
    UserAvatar: typeof import('./components/user/UserAvatar.vue')['default']
    UserList: typeof import('./components/user/UserList.vue')['default']
    UsersAvatars: typeof import('./components/user/UsersAvatars.vue')['default']
    XIcon: typeof import('./components/icons/XIcon.vue')['default']
  }
}
